"""Builds queue/002-chhupan-chhupai.json (Tall-Tale Original #1). Run: python scripts/stories/chhupan_chhupai.py"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
N = "narrator"

characters = [
    {"id": "madho", "name": "Madho", "role": "old_man", "gender": "male", "voice": "hi-IN-MadhurNeural",
     "look": "thin Indian man about 50, grey stubble, tired kind eyes, faded brown kurta and a wool shawl"},
    {"id": "madho_child", "name": "Little Madho (1986)", "role": "child_boy", "gender": "male", "voice": "hi-IN-MadhurNeural",
     "look": "8-year-old Indian village boy, thin, messy hair, torn half-sleeve shirt and shorts, big eyes"},
    {"id": "gauri", "name": "Gauri (ghost)", "role": "child_girl", "gender": "female", "voice": "hi-IN-SwaraNeural",
     "eleven_settings": {"stability": 0.72, "style": 0.15},
     "look": "8-year-old Indian girl ghost in a faded red lehenga and silver anklets, long dusty black hair, "
             "pale grey skin, dark hollow eyes, thin long grey fingers"},
    {"id": "gauri_young", "name": "Gauri (1986)", "role": "child_girl", "gender": "female", "voice": "hi-IN-SwaraNeural",
     "eleven_settings": {"stability": 0.6, "style": 0.3},
     "look": "cheerful 8-year-old Indian girl in a bright red lehenga, braided hair with red ribbons, silver anklets"},
    {"id": "banwari", "name": "Banwari", "role": "elder", "gender": "male", "voice": "hi-IN-MadhurNeural",
     "look": "round-faced Indian cook in his 60s, white moustache, vest and apron, towel on his shoulder"},
    {"id": "meenakshi", "name": "Meenakshi Rathore", "role": "young_woman", "gender": "female", "voice": "hi-IN-SwaraNeural",
     "look": "confident Indian woman about 30, district officer, crisp cotton saree, glasses, holding files"},
    {"id": "harilal", "name": "Munim Harilal", "role": "villain", "gender": "male", "voice": "hi-IN-MadhurNeural",
     "look": "thin sly Indian accountant in his 50s, black cap, round spectacles, ledger under his arm, 1980s"},
    {"id": "thakur", "name": "Thakur", "role": "authority", "gender": "male", "voice": "hi-IN-MadhurNeural",
     "look": "stern Indian landlord in his 50s, thick moustache, white turban, silk sherwani, 1980s"},
    {"id": "ramdeen", "name": "Ramdeen (the gardener)", "role": "elder", "gender": "male", "voice": "hi-IN-MadhurNeural",
     "look": "poor thin Indian gardener in a dhoti, frightened, 1980s"},
    {"id": "sarpanch", "name": "Sarpanch", "role": "authority", "gender": "male", "voice": "hi-IN-MadhurNeural",
     "look": "elderly village headman, white beard, white dhoti kurta, angry, holding a burning torch"},
    {"id": "kallu", "name": "Kallu", "role": "friend", "gender": "male", "voice": "hi-IN-MadhurNeural",
     "look": "skinny drunk village man in a checked lungi, messy hair"},
    {"id": "golu", "name": "Golu", "role": "child_boy", "gender": "male", "voice": "hi-IN-MadhurNeural",
     "look": "8-year-old village boy in striped pyjamas, eyes closed, sleepwalking"},
]

V = "remote Bundelkhand village of Sunarpur, rocky hills, mud and stone houses"
H = "old Raunakpur haveli turned government circuit house, carved sandstone arches, long corridors"
FB = "1986 flashback, warm faded colours"

# (id, setting, characters, mood, sfx, [(speaker, hindi, english[, shot])])
scenes = [
    ("s01", f"a narrow dark lane in the {V} at night, every doorframe marked with a hundred small white chalk lines",
     [], "dread", [], [
        (N, "बुंदेलखंड के सुनारपुर गाँव में, अमावस की रातों को कोई दरवाज़ा नहीं खोलता।",
         "In the village of Sunarpur in Bundelkhand, nobody opens a door on moonless nights."),
        (N, "हर घर की चौखट पर चॉक से सौ छोटी-छोटी लकीरें खिंची रहती हैं।",
         "On every doorframe, a hundred little chalk lines are drawn.",
         "extreme close-up of a hundred small white chalk tally lines on an old wooden doorframe"),
        (N, "और इस गाँव में एक खेल पर पूरी तरह पाबंदी है… छुपन-छुपाई।",
         "And one game is completely forbidden here… hide and seek."),
    ]),
    ("s02", f"empty village lane at night in the {V}, a drunk man staggering, a lantern on a wall", ["kallu"], "dread",
     ["anklet"], [
        (N, "उस रात कल्लू ताड़ी के ठेके से लड़खड़ाता हुआ घर लौट रहा था।",
         "That night, Kallu was staggering home from the toddy shop."),
        (N, "गली सुनसान थी। कुत्ते भी चुप थे।", "The lane was deserted. Even the dogs were silent."),
        (N, "तभी पीछे से पायल की आवाज़ आई। छम… छम… छम।", "Then, behind him, anklets. Chham… chham… chham.",
         "close-up of small bare feet with silver anklets walking on a dusty lane at night"),
        ("gauri", "माधो… बाहर आओ… खेलें?", "Madho… come out… shall we play?"),
        ("kallu", "माधो? अरे मैं माधो नहीं हूँ। पर चल, खेलते हैं! हाँ!",
         "Madho? I'm not Madho. But fine, let's play! Yes!"),
        (N, "उसने हँसते हुए हाँ कह दिया।", "Laughing, he said yes."),
    ]),
    ("s03", f"the courtyard of the {H} at dawn, a man facing the wall with eyes shut", ["kallu"], "drone", [], [
        (N, "सुबह गाँव वालों ने उसे पुरानी हवेली के आँगन में पाया।",
         "At dawn, the villagers found him in the courtyard of the old haveli."),
        (N, "दीवार की तरफ़ मुँह करके, आँखें बंद, धीरे-धीरे गिनते हुए।",
         "Facing the wall, eyes shut, slowly counting."),
        ("kallu", "अट्ठानवे… निन्यानवे… सौ।", "Ninety-eight… ninety-nine… a hundred."),
        (N, "उस दिन के बाद कल्लू ने कभी एक शब्द नहीं बोला।", "After that day, Kallu never spoke another word."),
    ]),
    ("s04", f"a battered state bus stopping at dusk on a dusty road near the {V}, a lone man stepping down with a cloth bag",
     ["madho"], "calm", [], [
        (N, "चालीस साल। इतने बरसों से सुनारपुर इस खेल के साथ जी रहा था।",
         "Forty years. For forty years Sunarpur had lived with this game."),
        (N, "और उसी हफ़्ते, शाम की आख़िरी बस से एक अजनबी गाँव में उतरा।",
         "And that same week, a stranger stepped off the last evening bus."),
        (N, "नाम था माधो। उम्र पचास के आसपास। ना कोई घर, ना कोई परिवार।",
         "His name was Madho. About fifty. No home, no family."),
        (N, "ज़िला दफ़्तर ने उसे रौनकपुर हवेली का चौकीदार बनाकर भेजा था।",
         "The district office had sent him as the caretaker of Raunakpur Haveli."),
        ("madho", "बस एक कमरा, दो वक़्त की रोटी, और थोड़ी शांति। और क्या चाहिए।",
         "Just a room, two meals a day and a little peace. What more does a man need?"),
    ]),
    ("s05", f"the {H} at sunset, its east wing dark with a rusted lock and chains", [], "dread", [], [
        (N, "रौनकपुर हवेली कभी ठाकुरों की शान थी।", "Raunakpur Haveli was once the pride of the Thakurs."),
        (N, "तीस साल पहले सरकार ने इसे सर्किट हाउस बना दिया।", "Thirty years ago, the government made it a circuit house."),
        (N, "पर इतने दूर गाँव में अफ़सर कम ही आते थे। हवेली ज़्यादातर ख़ाली पड़ी रहती।",
         "But officials rarely came to so remote a village. The haveli mostly stood empty."),
        (N, "और उसका पूरब वाला हिस्सा… उस पर तब से ताला लगा था, जब से किसी को याद है।",
         "And its east wing… had been locked for as long as anyone could remember.",
         "close-up of a huge rusted padlock and chains on a carved wooden door"),
    ]),
    ("s06", f"smoky old kitchen of the {H}, clay stove, brass pots, lantern light", ["banwari", "madho"], "calm", [], [
        ("banwari", "आ गए भैया? मैं बनवारी, यहाँ का रसोइया। चालीस साल से इसी हवेली में रोटियाँ बेल रहा हूँ।",
         "You're here, brother? I'm Banwari, the cook. Forty years I've been rolling rotis in this haveli."),
        ("madho", "इतनी बड़ी हवेली, और इतनी ख़ामोश?", "Such a big haveli, and so silent?"),
        ("banwari", "ख़ामोश ही अच्छी है भैया। बस एक बात याद रखना।", "Silent is good, brother. Just remember one thing."),
        ("banwari", "पूरब वाले हिस्से की तरफ़ मत जाना। और रात को कोई तुम्हारा नाम पुकारे, तो जवाब मत देना।",
         "Don't go near the east wing. And if someone calls your name at night, don't answer."),
        ("madho", "और गाँव के दरवाज़ों पर ये लकीरें? ये कैसा टोटका है?",
         "And those lines on every door in the village? What superstition is that?"),
        ("banwari", "टोटका नहीं भैया, जान बचाने का तरीका है। सौ लकीरें मतलब गिनती पूरी।",
         "Not superstition, brother. It's how we stay alive. A hundred lines means the count is done."),
        ("banwari", "वो समझती है कि यहाँ कोई नहीं छुपा, और आगे बढ़ जाती है।",
         "She thinks nobody is hiding there, and moves on."),
        ("madho", "वो? कौन वो?", "She? Who is she?"),
        ("banwari", "ठाकुर साहब की बिटिया… गौरी।", "The Thakur's little daughter… Gauri."),
    ]),
    ("s07", f"Banwari telling a story by lantern light in the kitchen of the {H}, shadows on the wall",
     ["banwari", "madho"], "dread", [], [
        ("banwari", "चालीस साल पहले, एक रात गौरी बिटिया ग़ायब हो गई। उसी रात ठकुराइन के गहने भी।",
         "Forty years ago, little Gauri vanished one night. The Thakurain's jewels vanished the same night."),
        ("banwari", "सबने कहा, माली और उसका परिवार चोरी करके बिटिया को भी उठा ले गए।",
         "Everyone said the gardener's family stole them and took the girl too."),
        ("banwari", "गाँव वालों ने उन्हें उसी रात मार-पीट कर गाँव से निकाल दिया।",
         "The villagers beat them and threw them out of the village that same night."),
        ("banwari", "बिटिया फिर कभी नहीं मिली। पर उसकी आवाज़… वो आज भी गलियों में घूमती है।",
         "The girl was never found. But her voice… it still walks the lanes."),
        (N, "माधो हँस दिया। पर पता नहीं क्यों, उसके हाथ ठंडे पड़ गए थे।",
         "Madho laughed. But somehow, his hands had gone cold."),
        (N, "और हवेली की सीढ़ियों पर उसे पहले से पता था कि कौन सी सीढ़ी चरमराएगी।",
         "And on the haveli stairs, he already knew which step would creak."),
    ]),
    ("s08", f"a white government jeep arriving in the dusty forecourt of the {H} in the morning", ["meenakshi", "banwari"],
     "pulse", [], [
        (N, "अगली सुबह हवेली में महीनों बाद कोई मेहमान आया।", "The next morning, the haveli had its first guest in months."),
        ("meenakshi", "मैं मीनाक्षी राठौर, ज़िला प्रशासन से। ये हवेली सात दिन बाद नीलाम होनी है।",
         "I'm Meenakshi Rathore, district administration. This haveli goes to auction in seven days."),
        ("meenakshi", "मुझे इसका हर कमरा देखना है। पूरब वाला हिस्सा भी।",
         "I need to see every room. The east wing too."),
        ("banwari", "मैडम जी, वो हिस्सा तो चालीस साल से बंद है। चाबी भी किसी के पास नहीं।",
         "Madam, that wing has been shut for forty years. Nobody even has the key."),
        ("meenakshi", "तो ताला तोड़ेंगे। सात दिन में सब ख़ाली चाहिए।",
         "Then we'll break the lock. Everything must be cleared in seven days."),
        (N, "सात दिन। और सातवीं रात… अमावस थी।", "Seven days. And the seventh night… was a moonless night."),
    ]),
    ("s09", f"a long dark corridor of the {H} at night, a man with a kerosene lantern near a locked wall", ["madho"],
     "dread", [], [
        (N, "पहली रात। माधो लालटेन लेकर गलियारे का आख़िरी चक्कर लगा रहा था।",
         "The first night. Madho was doing his last round of the corridor with a lantern."),
        (N, "पूरब वाले हिस्से की दीवार के पीछे से एक बच्ची की आवाज़ आई।",
         "From behind the east wing's wall came a little girl's voice."),
        ("gauri", "एक… दो… तीन… चार…", "One… two… three… four…"),
        (N, "कोई गिन रहा था। धीरे-धीरे। बहुत धीरे।", "Someone was counting. Slowly. Very slowly."),
        ("madho", "कौन है वहाँ?", "Who's there?"),
        (N, "गिनती रुक गई। और फिर हवा की सीटी के सिवा कुछ नहीं।",
         "The counting stopped. Then nothing but the whistle of the wind."),
        ("madho", "हवा है। पुरानी हवेली है, हवा तो बोलेगी ही।",
         "Just the wind. It's an old haveli, the wind will talk."),
    ]),
    ("s10", f"the stone courtyard of the {H} in morning light, a freshly drawn chalk hopscotch with small wet footprints",
     ["banwari", "madho"], "dread", [], [
        (N, "दूसरी सुबह आँगन में किसी ने चॉक से लंगड़ी टाँग का खेल बनाया था।",
         "On the second morning, someone had drawn a hopscotch in chalk in the courtyard.",
         "top-down view of a fresh chalk hopscotch on old stone tiles"),
        (N, "चॉक एकदम ताज़ी थी। और खानों के बीच छोटे-छोटे गीले पैरों के निशान थे।",
         "The chalk was fresh. And between the squares were small wet footprints."),
        ("banwari", "हे भगवान… ये तो वही खेल है। बिटिया यही खेलती थी।",
         "Oh God… that's the same game. The little one used to play it."),
        ("banwari", "भैया, आज से मैं अंधेरा होने से पहले घर चला जाऊँगा। माफ़ करना।",
         "Brother, from today I'm going home before dark. Forgive me."),
        ("madho", "किसी गाँव के बच्चे की शरारत होगी, बनवारी।", "Must be some village kid's prank, Banwari."),
        ("banwari", "इस गाँव के बच्चे शाम को घर से बाहर नहीं निकलते, भैया।",
         "Children in this village don't step out after dusk, brother."),
    ]),
    ("s11", f"village children being pulled indoors by their mothers at dusk in the {V}, doors with chalk lines",
     [], "drone", [], [
        (N, "सुनारपुर में बच्चों को पहला सबक यही सिखाया जाता है।",
         "In Sunarpur, this is the first lesson every child learns."),
        (N, "अंधेरे में अपना नाम सुनो, तो जवाब मत दो।", "If you hear your name in the dark, don't answer."),
        (N, "दरवाज़ा कोई खटखटाए, तो खोलो मत।", "If someone knocks, don't open the door."),
        (N, "और कभी, कभी भी, छुपन-छुपाई मत खेलो।", "And never, ever play hide and seek."),
        (N, "क्योंकि इस गाँव में एक खिलाड़ी आज भी अपनी बारी का इंतज़ार कर रही है।",
         "Because in this village, one player is still waiting for her turn."),
    ]),
    ("s12", f"the flat roof and dark staircase of the {H} on the third night, moonlight, a small shadow running",
     ["madho"], "chase", ["anklet"], [
        (N, "तीसरी रात छत पर किसी के भागने की आवाज़ आई। छम… छम… छम।",
         "On the third night, something ran across the roof. Chham… chham… chham."),
        ("gauri", "पकड़ो! पकड़ो ना!", "Catch me! Come on, catch me!"),
        (N, "फिर एक बच्ची की खिलखिलाहट। ठीक उसके कमरे के ऊपर।",
         "Then a little girl's giggle. Right above his room."),
        (N, "माधो भागकर अपने कमरे में पहुँचा। उसके बिस्तर पर कुछ रखा था।",
         "Madho ran back to his room. Something was lying on his bed."),
        (N, "एक लाल रंग का लकड़ी का लट्टू। पुराना, घिसा हुआ।", "A red wooden spinning top. Old, worn smooth.",
         "close-up of an old red wooden spinning top lying on a white bedsheet in lantern light"),
        (N, "उसे हाथ में लेते ही माधो के हाथ काँपने लगे। क्यों, ये उसे ख़ुद नहीं पता था।",
         "The moment he held it, his hands began to shake. He didn't know why."),
        ("gauri", "माधो… तुम आ गए!", "Madho… you came back!"),
    ]),
    ("s13", f"village lanes of the {V} at night, a pale girl's silhouette skipping between houses", [], "dread",
     ["anklet"], [
        (N, "उस रात गाँव में भी कुछ बदल गया।", "That night, something changed in the village too."),
        (N, "अब गलियों में घूमती आवाज़ सवाल नहीं पूछ रही थी। अब वो ख़ुश थी।",
         "The voice in the lanes was no longer asking. Now it was happy."),
        ("gauri", "माधो आ गया! माधो आ गया!", "Madho is back! Madho is back!"),
        (N, "सुबह सरपंच का आठ साल का पोता गोलू अपने बिस्तर से ग़ायब था।",
         "By morning, the sarpanch's eight-year-old grandson Golu was missing from his bed."),
        (N, "उसे हवेली के आँगन में पाया गया। दीवार की तरफ़ मुँह, आँखें बंद।",
         "He was found in the haveli courtyard. Facing the wall, eyes shut."),
        ("golu", "सत्तानवे… अट्ठानवे… निन्यानवे…", "Ninety-seven… ninety-eight… ninety-nine…"),
    ]),
    ("s14", f"village council under a huge banyan tree in the {V}, angry villagers, an outsider standing alone",
     ["sarpanch", "madho", "banwari"], "pulse", [], [
        ("sarpanch", "जब से ये अजनबी आया है, वो बेचैन है। पहले कभी बच्चों को नहीं ले गई!",
         "Ever since this stranger came, she's restless. She never took children before!"),
        ("sarpanch", "अमावस से पहले ये आदमी गाँव छोड़ दे। वरना हम ख़ुद निकालेंगे।",
         "This man leaves the village before the dark moon. Or we throw him out ourselves."),
        ("madho", "मैंने क्या किया है? मैं तो इस गाँव को जानता भी नहीं।",
         "What have I done? I don't even know this village."),
        ("banwari", "भैया, चालीस साल पहले भी इसी चौपाल पर एक परिवार को ऐसे ही निकाला गया था।",
         "Brother, forty years ago a family was thrown out from this very spot, just like this."),
        (N, "माधो के सिर में तेज़ दर्द उठा। जैसे कोई भूली हुई याद अंदर से दरवाज़ा पीट रही हो।",
         "A sharp pain split Madho's head. As if a forgotten memory was banging on a door inside."),
    ]),
    ("s15", "a dusty district records room, stacks of old files, a woman reading a yellowed 1986 police report",
     ["meenakshi"], "drone", [], [
        (N, "उधर मीनाक्षी ज़िला दफ़्तर की पुरानी फ़ाइलें पलट रही थी।",
         "Meanwhile, Meenakshi was going through the district office's old files."),
        ("meenakshi", "1986 की पुलिस रिपोर्ट। ठाकुर की बेटी गौरी लापता। ठकुराइन के गहने चोरी।",
         "A 1986 police report. The Thakur's daughter Gauri missing. The Thakurain's jewels stolen.",
         "close-up of a yellowed typed police report with a faded photo of a little girl"),
        ("meenakshi", "शक माली रामदीन पर। उसी रात परिवार को गाँव से निकाला गया।",
         "Suspect: Ramdeen, the gardener. His family thrown out of the village that night."),
        ("meenakshi", "रामदीन, उसकी पत्नी… और एक आठ साल का बेटा।", "Ramdeen, his wife… and an eight-year-old son."),
        ("meenakshi", "बेटे का नाम… माधो।", "The son's name… Madho."),
    ]),
    ("s16", f"the veranda of the {H} at dusk, a woman with files confronting a tired caretaker", ["meenakshi", "madho"],
     "drone", [], [
        ("meenakshi", "माधो जी, आप कहाँ के रहने वाले हैं? आपके पिता का नाम क्या था?",
         "Madho ji, where are you from? What was your father's name?"),
        ("madho", "मुझे याद नहीं, मैडम। बचपन का कुछ भी याद नहीं।", "I don't remember, madam. Nothing from my childhood."),
        ("madho", "बस इतना याद है कि एक रात बहुत शोर था। मशालें थीं। कोई रो रहा था।",
         "Only that one night there was a lot of noise. Burning torches. Someone was crying."),
        ("meenakshi", "आप इसी गाँव के हैं, माधो जी। आप रामदीन माली के बेटे हैं।",
         "You're from this village, Madho ji. You're Ramdeen the gardener's son."),
    ]),
    ("s17", f"{FB}: two children playing in the sunlit east wing of the haveli, a small storeroom door",
     ["madho_child", "gauri_young"], "calm", [], [
        (N, "उस रात माधो को सपना आया। या शायद… याद।", "That night Madho had a dream. Or perhaps… a memory."),
        ("madho_child", "गौरी, जल्दी छुप जा! मैं सौ तक गिनूँगा, फिर ढूँढूँगा!",
         "Gauri, hide quickly! I'll count to a hundred, then I'll find you!"),
        ("gauri_young", "मुझे कोई नहीं ढूँढ पाएगा!", "Nobody can ever find me!"),
        (N, "छोटा माधो गौरी को पूरब वाले हिस्से की एक छोटी सी कोठरी में छुपाता है।",
         "Little Madho hides Gauri in a tiny storeroom in the east wing."),
        ("madho_child", "रुक, मैं बाहर से कुंडी लगा देता हूँ। फिर तो कोई नहीं ढूँढ पाएगा!",
         "Wait, I'll latch it from outside. Then nobody will ever find you!"),
        (N, "कुंडी लगी। माधो गिनने लगा। एक… दो… तीन…", "The latch clicked shut. Madho began to count. One… two… three…",
         "extreme close-up of a small child's hand sliding an old iron latch shut"),
        (N, "और तभी नीचे से चीख़ें आईं।", "And then the screaming started downstairs."),
    ]),
    ("s18", f"{FB}: a sly accountant opening an iron safe in the haveli at night, gold jewellery glinting",
     ["harilal", "thakur", "ramdeen"], "pulse", [], [
        (N, "उसी शाम मुनीम हरिलाल ने ठकुराइन की तिजोरी से सारे गहने निकाल लिए थे।",
         "That same evening, Munim Harilal had emptied the Thakurain's safe."),
        ("harilal", "चोरी हुई है तो चोर भी चाहिए। और माली से अच्छा चोर कौन?",
         "If there's a theft, there must be a thief. And who better than the gardener?"),
        ("harilal", "ठाकुर साहब, गहने तो माली के परिवार ने चुराए हैं। मैंने अपनी आँखों से देखा।",
         "Thakur sahib, the gardener's family stole the jewels. I saw it with my own eyes."),
        ("thakur", "रामदीन! हमारे नमक का ये बदला?", "Ramdeen! Is this how you repay us?"),
        ("ramdeen", "मैंने चोरी नहीं की, ठाकुर साहब! भगवान की क़सम!", "I didn't steal anything, Thakur sahib! I swear to God!"),
        ("thakur", "और बिटिया कहाँ है? गौरी कहाँ है?", "And where is my daughter? Where is Gauri?"),
        ("harilal", "वो भी इन्हीं के साथ थी, हुज़ूर। ज़रूर इन्होंने ही…", "She was with them, sir. They must have…"),
    ]),
    ("s19", f"{FB}: an angry mob with burning torches and sticks dragging a poor family out of the village at night",
     ["madho_child"], "chase", ["crowd"], [
        (N, "किसी ने एक नहीं सुनी। लाठियाँ उठीं। मशालें जलीं।", "No one listened. Sticks were raised. Torches were lit."),
        (N, "रामदीन, उसकी पत्नी और रोता हुआ छोटा माधो आधी रात को गाँव से धकेल दिए गए।",
         "Ramdeen, his wife and a sobbing little Madho were driven out of the village at midnight."),
        ("madho_child", "बापू! गौरी… गौरी ऊपर है! मुझे उसे ढूँढना है!", "Father! Gauri… Gauri is upstairs! I have to find her!"),
        (N, "पर उस शोर में एक बच्चे की आवाज़ कौन सुनता।", "But who hears a child in that kind of noise?"),
        (N, "और ऊपर, अंधेरी कोठरी में, एक बच्ची चुपचाप इंतज़ार कर रही थी।",
         "And upstairs, in a dark storeroom, a little girl waited quietly."),
        ("gauri_young", "माधो… सौ हो गया? ढूँढो ना…", "Madho… is it a hundred yet? Come find me…"),
    ]),
    ("s20", f"{FB}: villagers searching a well, fields and a river bank with lanterns, the haveli east wing dark behind",
     [], "piano", [], [
        (N, "गौरी को हर जगह ढूँढा गया। कुएँ में, खेतों में, नदी के किनारे।",
         "They searched for Gauri everywhere. The well, the fields, the riverbank."),
        (N, "पर उस कोठरी में किसी ने नहीं झाँका, जिसकी कुंडी बाहर से लगी थी।",
         "But no one looked into the storeroom latched from outside."),
        (N, "महीने भर बाद ठकुराइन दुख में चल बसीं। और ठाकुर ने पूरब वाला हिस्सा हमेशा के लिए बंद करवा दिया।",
         "A month later the Thakurain died of grief. And the Thakur had the east wing sealed forever."),
        (N, "उस रात के डर और मार में छोटा माधो सब भूल गया। गौरी को भी। उस कुंडी को भी।",
         "In the terror and beatings of that night, little Madho forgot everything. Gauri. And that latch."),
    ]),
    ("s21", f"a man waking up crying in a dark room of the {H}, holding a red wooden spinning top", ["madho"], "piano", [], [
        ("madho", "मैंने कुंडी लगाई थी… मैंने ही…", "I latched that door… it was me…"),
        ("madho", "गौरी… चालीस साल से तुम वहीं…", "Gauri… for forty years you've been in there…"),
        (N, "माधो फूट-फूटकर रोने लगा। बाहर, गलियों में, पायल फिर बज रही थी।",
         "Madho broke down sobbing. Outside, in the lanes, the anklets were ringing again."),
    ]),
    ("s22", f"moonless night, villagers with burning torches marching towards the {H}", ["sarpanch"], "chase",
     ["crowd"], [
        (N, "सातवीं रात। अमावस।", "The seventh night. The dark moon."),
        (N, "गाँव वाले मशालें लेकर हवेली की तरफ़ बढ़ रहे थे। माधो को निकालने।",
         "The villagers marched on the haveli with torches. To throw Madho out."),
        ("sarpanch", "निकालो इसे! आज रात ये गाँव में नहीं रहेगा!", "Throw him out! He won't stay in this village tonight!"),
        (N, "बिल्कुल वैसे ही, जैसे चालीस साल पहले।", "Exactly like forty years ago."),
    ]),
    ("s23", f"doors swinging open by themselves in the {V} at night, chalk lines fading, sleepwalking children "
            "in a line walking towards the haveli", ["golu", "sarpanch", "gauri"], "chase", ["anklet"], [
        (N, "पर उसी रात गौरी भी गाँव में आई। पहली बार, पूरे ग़ुस्से में।",
         "But that same night, Gauri came to the village. For the first time, in full fury."),
        (N, "चॉक की लकीरें अपने आप मिटने लगीं। दरवाज़े अपने आप खुलने लगे।",
         "The chalk lines began to wipe themselves away. Doors swung open on their own.",
         "close-up of chalk tally lines on a doorframe dissolving into dust"),
        (N, "और घरों से बच्चे निकलने लगे। नींद में चलते हुए। आँखें बंद। गिनते हुए।",
         "And children walked out of their homes. Asleep. Eyes shut. Counting."),
        ("golu", "एक… दो… तीन…", "One… two… three…"),
        ("sarpanch", "रोको इन्हें! कोई रोको!", "Stop them! Someone stop them!"),
        (N, "पर बड़ों के पैर ज़मीन से चिपक गए थे। कोई हिल नहीं पा रहा था।",
         "But the grown-ups' feet were stuck to the ground. No one could move."),
        ("gauri", "किसी ने मुझे नहीं ढूँढा। अब कोई घर नहीं जाएगा।", "Nobody came to find me. Now nobody goes home."),
    ]),
    ("s24", f"a man and a woman breaking a rusted lock on the sealed east wing of the {H}, dust exploding in torchlight",
     ["madho", "meenakshi"], "chase", [], [
        ("madho", "मीनाक्षी जी, पूरब वाला हिस्सा! मुझे पता है वो कहाँ है!",
         "Meenakshi ji, the east wing! I know where she is!"),
        (N, "माधो और मीनाक्षी ने ताला तोड़ा। चालीस साल की धूल उड़ी।",
         "Madho and Meenakshi broke the lock. Forty years of dust rose up."),
        (N, "गलियारे के आख़िर में एक छोटी सी कोठरी। दरवाज़े पर कुंडी, अब भी बाहर से लगी।",
         "At the end of the corridor, a tiny storeroom. Its latch still shut from the outside.",
         "close-up of an old iron latch shut from outside on a small dusty wooden door"),
    ]),
    ("s25", "inside a tiny dusty storeroom, a faded red child's lehenga and a silver anklet on the floor, "
            "scratch marks on the back of the door", ["madho", "meenakshi"], "reveal", [], [
        (N, "माधो के हाथ काँप रहे थे। उसने कुंडी खोली।", "Madho's hands were shaking. He opened the latch."),
        (N, "अंदर एक छोटा सा लाल लहँगा पड़ा था। और एक पायल।", "Inside lay a small red lehenga. And one anklet."),
        (N, "और दरवाज़े के अंदर की तरफ़… नाख़ूनों से खुरची हुई लकीरें।",
         "And on the inside of the door… lines scratched with fingernails.",
         "extreme close-up of a hundred thin tally lines scratched into old wood by small fingernails"),
        ("meenakshi", "ये गिनती है। सौ लकीरें।", "It's a count. A hundred lines."),
        (N, "सौ लकीरें। ठीक वैसी ही, जैसी चालीस साल से गाँव हर दरवाज़े पर बना रहा था।",
         "A hundred lines. Exactly like the ones the village had drawn on every door for forty years."),
        (N, "बिना जाने कि वो किसकी गिनती थी।", "Without ever knowing whose count it was."),
    ]),
    ("s26", "the dark storeroom, a small pale ghost girl standing in the corner with dust in her hair, a kneeling man",
     ["gauri", "madho"], "reveal", ["anklet"], [
        (N, "कोठरी में ठंडी हवा का झोंका आया। और कोने में वो खड़ी थी।",
         "A cold gust swept the storeroom. And there she stood, in the corner."),
        (N, "एक छोटी सी बच्ची। बालों में धूल। आँखों में चालीस साल का इंतज़ार।",
         "A little girl. Dust in her hair. Forty years of waiting in her eyes."),
        ("gauri", "तुम बहुत देर से आए, माधो। मैं कब से छुपी थी।", "You came so late, Madho. I've been hiding for so long."),
        ("madho", "मुझे माफ़ कर दे, गौरी। मैं भूल गया था। मैं बच्चा था।",
         "Forgive me, Gauri. I forgot. I was just a child."),
        ("gauri", "सब भूल गए। किसी ने मुझे नहीं ढूँढा।", "Everyone forgot. Nobody came to find me."),
    ]),
    ("s27", "a man kneeling before a little ghost girl in a dusty storeroom, first light of dawn through a crack",
     ["madho", "gauri"], "piano", [], [
        (N, "माधो घुटनों के बल बैठ गया। चालीस साल पुरानी गिनती आख़िर पूरी हुई।",
         "Madho sank to his knees. A forty-year-old count was finally complete."),
        ("madho", "मिल गई, गौरी। मैंने तुम्हें ढूँढ लिया।", "Found you, Gauri. I found you."),
        (N, "गौरी के चेहरे पर पहली बार मुस्कान आई।", "For the first time, Gauri smiled."),
        ("gauri", "तुम जीत गए, माधो।", "You win, Madho."),
        (N, "और वो धीरे-धीरे सुबह की रोशनी में घुल गई। पायल की आख़िरी छम-छम के साथ।",
         "And she slowly dissolved into the morning light, with one last chime of her anklets."),
    ]),
    ("s28", f"dawn in the {V}, children waking up in the lanes and running to their mothers, torches burnt out",
     [], "piano", [], [
        (N, "उसी पल गाँव की गलियों में बच्चों की आँखें खुल गईं।",
         "At that very moment, the children in the lanes opened their eyes."),
        (N, "कोई रो रहा था, कोई अपनी माँ से लिपटा था। गोलू भी घर लौट आया था।",
         "Some were crying, some clung to their mothers. Golu was home too."),
        (N, "मशालें बुझ चुकी थीं। किसी में माधो की तरफ़ देखने की हिम्मत नहीं थी।",
         "The torches had burned out. No one had the courage to look Madho in the eye."),
    ]),
    ("s29", f"a woman officer handing a stamped government letter to a teary caretaker on the steps of the {H}",
     ["meenakshi", "madho"], "piano", [], [
        (N, "मीनाक्षी की रिपोर्ट ने चालीस साल पुराना सच बाहर ला दिया।",
         "Meenakshi's report brought a forty-year-old truth into the light."),
        (N, "ठकुराइन के गहने मुनीम हरिलाल के पुश्तैनी संदूक में मिले।",
         "The Thakurain's jewels were found in Munim Harilal's family chest."),
        ("meenakshi", "रामदीन माली बेक़सूर थे, माधो जी। सरकार ये बात लिखकर देगी।",
         "Ramdeen the gardener was innocent, Madho ji. The government will put it in writing."),
        ("madho", "बापू को ये सुनना था, मैडम। चालीस साल देर हो गई।",
         "My father needed to hear this, madam. Forty years too late."),
        (N, "उस सुबह सुनारपुर ने पहली बार अपने दरवाज़ों से चॉक की लकीरें धो डालीं।",
         "That morning, for the first time, Sunarpur washed the chalk lines off its doors."),
    ]),
    ("s30", f"months later, village children playing hide and seek at dusk near the renovated {H}, one boy counting "
            "against a tree", ["golu", "gauri"], "dread", ["laugh"], [
        (N, "कुछ महीने बाद। हवेली अब होटल बनने जा रही है।", "A few months later. The haveli is becoming a hotel."),
        (N, "और सुनारपुर के बच्चे फिर से छुपन-छुपाई खेलने लगे हैं।",
         "And the children of Sunarpur play hide and seek again."),
        (N, "एक शाम एक छोटा लड़का पेड़ से मुँह सटाकर गिन रहा था।",
         "One evening, a little boy was counting with his face pressed to a tree."),
        ("golu", "अट्ठानवे… निन्यानवे… सौ!", "Ninety-eight… ninety-nine… a hundred!"),
        (N, "उसने आँखें खोलीं। सामने एक लड़की खड़ी थी, जिसे उसने पहले कभी नहीं देखा था।",
         "He opened his eyes. A girl he had never seen before stood in front of him."),
        ("gauri", "अब मेरी बारी… आँखें बंद करो।", "My turn now… close your eyes."),
    ]),
]

story = {
    "id": "002-chhupan-chhupai",
    "title": "She Is Still Counting to 100 | Hindi Horror Story",
    "genre": "horror",
    "art_style": "creepy_comic",
    "language": "hi",
    "priority": True,
    "logline": "In a remote Bundelkhand village where hide and seek is forbidden, a ghost girl has been waiting "
               "forty years for the boy who never came to find her.",
    "characters": characters,
    "scenes": [
        {"id": sid, "setting": setting, "characters": chars, "mood": mood,
         **({"sfx": sfx} if sfx else {}),
         "lines": [{"speaker": l[0], "text": l[1], "en": l[2], **({"shot": l[3]} if len(l) > 3 else {})}
                   for l in lines]}
        for sid, setting, chars, mood, sfx, lines in scenes
    ],
    "thumbnail": {
        "prompt": "a small pale ghost girl in a faded red lehenga peeking from behind a carved sandstone pillar in a dark "
                  "haveli corridor, one hollow eye visible, long grey fingers on the pillar, a hundred chalk lines on "
                  "the wall beside her, lantern glow",
        "text": "मत बोलना हाँ",
    },
    "shorts": [
        {"scenes": ["s02", "s03"], "title": "Never say yes when she calls your name",
         "hook": "close-up of small bare feet with silver anklets on a dark village lane, a man's shadow behind"},
        {"scenes": ["s11"], "title": "The one game this village has banned for 40 years",
         "hook": "a hundred chalk lines on an old wooden door, a small grey hand touching them"},
        {"scenes": ["s12"], "title": "She left a toy on his bed. He doesn't know why he's shaking",
         "hook": "an old red wooden spinning top on a white bedsheet, a pale child's hand placing it"},
        {"scenes": ["s25"], "title": "What they found behind the latched door",
         "hook": "an old iron latch on a small dusty door, scratch marks glowing faintly"},
    ],
    "youtube": {
        "description": "In Sunarpur, a remote village in Bundelkhand, every door carries a hundred chalk lines and "
                       "one game is forbidden: hide and seek. For forty years a little girl's voice has walked its "
                       "lanes on moonless nights, calling one name. Then a stranger called Madho arrives as the new "
                       "caretaker of the old haveli, and the game begins again.",
        "hashtags": ["#BundelkhandHorror", "#HideAndSeek"],
        "tags": ["hide and seek horror story", "haunted haveli story", "village ghost story hindi",
                 "bundelkhand horror", "ghost girl horror story", "chhupan chhupai horror",
                 "haveli horror story hindi", "village horror story hindi"],
    },
}

out = ROOT / "queue" / f"{story['id']}.json"
out.write_text(json.dumps(story, indent=2, ensure_ascii=False), encoding="utf-8")
print("wrote", out)
